version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres-dev
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: projetoAPI
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d 

volumes:
  pgdata:

